### ISSUE TITLE
generate help for sub commands within groups.

### ISSUE THREAD

**Issue by drobbins329** [Charly6596/Discord.Addons.CommandsExtension#5]
reply is always "command not found" for any commands within a group.

**Comment by Charly6596** [comment]
Thanks for reporting the issue, as you might have seen I didn't work on this project for a while, but I might take a look once I have some spare time.
I believe the issue is how the commands are found, if you want to fix it I could help with any questions you would have.

**Comment by MaxEtMoritz** [comment]
#6 should fix this.
